// i spent 28 mins typing each card out manually, ur welcome
const troops = [
    "Skeletons", 
    "Ice spirit", 
    "Fire Spirit", 
    "Electro Spirit",
    "Heal Spirit",
    "Goblins",
    "Bomber",
    "Spear Goblins",
    "Ice Golem",
    "Bats",
    "Wall Breakers",
    "Suspicious bush",
    "Berserker",
    "Knight",
    "Archers",
    "Minions",
    "Skeleton Army",
    "Ice Wizard",
    "Guards",
    "Princess",
    "Miner",
    "Mega Minion",
    "Dart Goblin",
    "Goblin Gang",
    "Bandit",
    "Royale Ghost",
    "Skeleton Barrel",
    "Fisherman",
    "Firecracker",
    "Elixir Golem",
    "Little Prince",
    "Goblin Machine",
    "Valkyrie",
    "Musketeer",
    "Baby Dragon",
    "Mini Pekka",
    "Furnace",
    "Hog Rider",
    "Dark Prince",
    "Lumberjack",
    "Battle Ram",
    "Inferno Dragon",
    "Electro Wizard",
    "Hunter",
    "Night Witch",
    "Zappies",
    "Flying Machine",
    "Magic Archer",
    "Mighty Miner",
    "Battle Healer",
    "Skeleton King",
    "Golden Knight",
    "Skeleton Dragons",
    "Mother Witch",
    "Pheonix",
    "Goblin Demolisher",
    "Rune Giant",
    "Giant",
    "Balloon",
    "Witch",
    "Barbarians",
    "Prince",
    "Wizard",
    "Minion Hord",
    "Bowler",
    "Executioner",
    "Ram Rider",
    "Rascals",
    "Cannon Cart",
    "Royale Hogs",
    "Electro Dragon",
    "Archer queen",
    "Monk",
    "Goblinstein",
    "Giant Skeleton",
    "Royale Giant",
    "Sparky",
    "Elite Barbarians",
    "Goblin Giant",
    "Boss Bandit",
    "Spirit Empress",
    "Pekka",
    "Lava Hound",
    "Royale Recruits",
    "Mega Knight",
    "Electro Giant",
    "Golem",
    "Three Musketeers",
];

const buildings = [
    "Cannon",
    "Tombstone",
    "Mortar",
    "Bomb Tower",
    "Tesla",
    "Goblin Cage",
    "Goblin Drill",
    "Goblin Hut",
    "Infero Tower",
    "Elixir Pump",
    "Xbow",
    "Barbarian Hut",
];

const spells = [
    "Mirror",
    "Rage",
    "Zap",
    "Log",
    "Barbarian Barrel",
    "Snowball",
    "Goblin Curse",
    "Arrows",
    "Goblin Barrel",
    "Tornado",
    "Clone",
    "Earthquake",
    "Royale Delivery",
    "Void",
    "Vines",
    "Fireball",
    "Freeze",
    "Poison",
    "Graveyard",
    "Rocket",
    "Lightning",
];

const tt = [
    "Princess Tower",
    "Cannoner",
    "Dagger Dutches",
    "Royal Chef",
];

const allCards = [...buildings, ...troops,...spells];

function getDeck(array, count){
    const random = array.slice().sort(() => 0.5 - Math.random());
    return random.slice(0, count);
}

const randomDeck = getDeck(allCards, 8);
const randomTT = tt[Math.floor(Math.random() * tt.length)];

console.log("Your randomized deck:", randomDeck.join(", "));
console.log("Tower troop for this deck:", randomTT);